CREATE TABLE students
(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) DEFAULT NULL,
furigana VARCHAR(100) DEFAULT NULL,
nickname VARCHAR(100) DEFAULT NULL,
address VARCHAR(100) DEFAULT NULL,
live VARCHAR(100) DEFAULT NULL,
age INT DEFAULT NULL,
gender VARCHAR(100) DEFAULT NULL,
remark VARCHAR(255) DEFAULT NULL,
is_deleted boolean
);

CREATE TABLE students_courses
(
id INT AUTO_INCREMENT PRIMARY KEY,
student_id INT DEFAULT NULL,
course_name VARCHAR(100) DEFAULT NULL,
start_date DATE DEFAULT NULL,
completion_date DATE DEFAULT NULL
);